name: publish

on:
  release:
    types:
      - created

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Lang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: Build
        run: make build && mv cl_cli cl_cli-linux
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'cl_cli*'
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Lang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: Build
        run: make build && mv cl_cli cl_cli-macos
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'cl_cli*'
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Lang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: Build
        run: |
         make build
         mv cl_cli cl_cli-windows.exe
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'cl_cli*'